name: imosys_flutter_package
description: "A flutter package for iMoSyS"
version: 0.0.13
homepage: "https://github.com/GehaziJenda/imosys_flutter_package"

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  dropdown_button2: ^2.3.9 #for drop downs
  extended_image: ^9.1.0 #for loading images
  flutter:
    sdk: flutter
  http: ^1.2.2 #for API calls
  http_parser: ^4.0.2 #for multipart uploads

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

executables:
  generate_structure: generate_structure

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
